### ISSUE TITLE
créer une page pour les documents presse

### ISSUE THREAD

**Issue by npettiaux** [EduCodeBe/educode.be#11]
créer une page presse.educode.be qui est aussi si possible educode.be/presse (je pense que le premier lien je dois le créer dans le dns) pour mettre les documents à remettre à la presse lundi matin

**Comment by mourad1081** [comment]
Oui, le premier lien est à créer depuis votre hébergeur normalement.

**Comment by mourad1081** [comment]
C'est fait. La page est accessible via localhost:5000/presse ainsi que via le nouveau bouton "document" dans la section "presse" de la page d'accueil.

Comme vous vouliez une description pour le document téléchargeable, il a fallu que je trick un peu lektor. Donc, pour ajouter un document, il faut procéder comme suit : 

1. Aller à la page d'accueil, cliquez sur "Presse" dans le menu à gauche, tout en bas.
2. Cliquez sur le "+" pour rajouter une sous-page. ** attention ** : vous devez rajouter une sous-page en choisissant le modèle "Document"
3. Vous pouvez décrire votre fichier dans l'input prévu à cet effet.
4. Save
5. Étant dans la sous-page dédié à ce document, vous devez maintenant joindre un fichier via le menu à gauche : "add attachment"
6. C'est fini, normalement le document apparaîtra dans la page de presse.

Si ne marche pas, n'hésitez pas à me contacter, je fournirai une rapide vidéo montrant les étapes.

**Comment by npettiaux** [comment]
merci beaucoup. Je regarde ce matin
