### ISSUE TITLE
ajouter le formulaire pour soumettre des stands et des ateliers

### ISSUE THREAD

**Issue by npettiaux** [EduCodeBe/educode.be#12]
#Adresse et lien HTML
https://framaforms.org/soumission-a-educode-1524690937

#Adresse et lien HTML avec ancre

 <a href="https://framaforms.org/soumission-a-educode-1524690937">Formulaire de proposition de stand pour le 27/8 ou d'atelier pour le 28/8 </a>

#Embarquer le code

<iframe src="https://framaforms.org/soumission-a-educode-1524690937" width="100%" height="800" 
border="0" ></iframe>

**Comment by mourad1081** [comment]
Dois-je supprimer le bouton "Soumettre ici" qui pointe vers https://educode2018.sciencesconf.org/ ?
