### ISSUE TITLE
uniformité de la page d'accueil

### ISSUE THREAD

**Issue by npettiaux** [EduCodeBe/educode.be#17]
Il faudrait que la page apparaisse vraiment uniforme. Par exemple, enlever tous les /* */ , { } qui introduisent les titres (même si cela fait référence au code, seuls les codeurs comprennent, les autres sont perdus par les changements).

En particulier aussi
* pour la page presse, mettre le titre dans la même couleur que les précédents et enlever le fond coloré
* pour les contacts, enlever la fin avec } coloré

**Comment by mourad1081** [comment]
C'est fait, n'hésitez pas à ré-ouvrir l'issue s'il s'avère que je doive encore retirer quelques trucs (comme certaines icônes par exemple)
