### ISSUE TITLE
logos des partenaires de la même taille et textes sans collision

### ISSUE THREAD

**Issue by npettiaux** [EduCodeBe/educode.be#19]
Les logos des partenaires devraient tous avoir la même taille et les textes ne devraient pas faire de collision (ils peuvent être repliés)

**Comment by mourad1081** [comment]
Je pense l'avoir corrigé, n'hésitez pas à réouvrir l'issue si jamais ça ne convient pas. (Difficile de faire correspondre la même dimension à des logos chacun de dimensions différentes)
