### ISSUE TITLE
Convertir l'HTML du tableau en Mardown

### ISSUE THREAD

**Issue by mourad1081** [EduCodeBe/educode.be#29]
De l'HTML pur a été placé dans un champ destiné à recevoir du markdown dans la section inscription. L'HTML génère un tableau, cependant c'est un document HTML complet qui a été écrit et non un simple tableau HTML.

Pour écrire des tableaux en markdown, il faut basiquement faire comme suit : 

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```
(Je le ferai moi-même mais plus tard si jamais cela pose soucis)

**Comment by npettiaux** [comment]
ok je le ferai simplement comme cela ! J'avais essayé mais avais un souci

**Comment by npettiaux** [comment]
fait avec html simple. Markdown pas assez souple
