### ISSUE TITLE
Quelles langues dois-je désactiver ?

### ISSUE THREAD

**Issue by mourad1081** [EduCodeBe/educode.be#7]
Pourriez-vous me rappeler quelle langue dois-je désactiver s'il vous plaît ?

**Comment by npettiaux** [comment]
ne laisser temporairement que le français et le néerlandais. Et stp m'expliquer comment tu fais, comme cela je pourrai réactiver facilement que nous aurons l'aide pour les traductions

**Comment by mourad1081** [comment]
Voilà, en dehors du FR et NL, tout est désactivé. Pour activer ou désactiver, il faut se rendre dans `templates/layout.html`

et commenter/décommenter les lignes qui affichent le bouton de la langue considérée.

Par exemple, si je désire désactiver le NL, je me rends à la ligne 123 (à l'heure où j'écris ce message) et je modifie 
```html
<a class="language-link {% if '/nl/' in this.url_path  %} {{ 'current' }} {% endif %}" href="{{ this.path | url(alt='nl') }}">
    <img width="16px" height="16px" src="{{ '/imgs/nl.png' | url }}" alt=""> NL
</a>
```

en commentant la ligne ainsi : 

```html
<!--
<a class="language-link {% if '/nl/' in this.url_path  %} {{ 'current' }} {% endif %}" href="{{ this.path | url(alt='nl') }}">
    <img width="16px" height="16px" src="{{ '/imgs/nl.png' | url }}" alt=""> NL
</a>
-->
```
